on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "test"
        run: pwd

      - name: "login to Docker hub"
        run: docker login --username youssefelaalem --password dckr_pat_zanoYG-VpZTtcLoIU3w-ME67_1Q
